"""empty message

Revision ID: 181472496faf
Revises: 
Create Date: 2020-08-11 19:01:24.712180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181472496faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.drop_index('name', table_name='role')
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.create_index('name', 'role', ['name'], unique=True)
    op.drop_index(op.f('ix_role_name'), table_name='role')
    # ### end Alembic commands ###
