"""empty message

Revision ID: 4f4a51ed65b5
Revises: fdce799a7472
Create Date: 2020-08-13 21:48:08.542197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4a51ed65b5'
down_revision = 'fdce799a7472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'location')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'avatar_hash')
    op.drop_column('user', 'age')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
